### ISSUE TITLE
Command + F delayed

### ISSUE THREAD

**Issue by JamsheedMistri** [MacPass/MacPass#1124]
**Describe the bug**
When I hit Command + F, I have to hit it multiple times before the search box is focused. This only started happening after I upgraded to macOS Big Sur.

**To Reproduce**
1. Open MacPass, enter master password
2. Focus anything other than the search bar (such as a password or entry)
3. Hit Command + F multiple times - the search box only focuses after ~2 seconds

**Expected behavior**
From anywhere in the program, Command + F should immediately focus the search field.

**Video**

https://user-images.githubusercontent.com/13024750/102955910-cd462000-448b-11eb-8167-752133fd88a0.mov

**Desktop (please complete the following information):**
 - macOS: 11.2 Beta (been happening since 11.0)
 - Version: 0.7.12

**Comment by bunducafe** [comment]
+1

But it occurs only with the macOS 11.x.

**Comment by mstarke** [comment]
Could you check out the current continous release and verify that the issue is fixed?

**Comment by JamsheedMistri** [comment]
The issue is fixed in the current continuous release. Thank you.

**Comment by JamsheedMistri** [comment]
This is fixed in the current continuous release. Thank you.

**Comment by JamsheedMistri** [comment]
@mstarke sorry, I didn't do extensive testing. This issue is still present but only in certain cases.

When focusing on an entry in MacPass, this bug is fixed. But, when focusing on a password field, this bug is not fixed.

Recreation steps:
1. Click on a password field
2. Command + F

Expected: Search is highlighted
Actual Result: Search is not highlighted until you wait 1-2 seconds. 

Since this is the same issue, I decided to comment here instead of opening a new issue. Let me know if you'd like me to open a new issue.
