### ISSUE TITLE
Password database file has changed after every access.

### ISSUE THREAD

**Issue by Vadammt** [MacPass/MacPass#685]
After closing my password database while only reading from it (no changes were saved) the database file has changed.
This isn't much of a deal, but I sync it with Seafile v6.0.7  and each time after closing the store, Seafile detects changes and uploads the "new" database to the server.

**tl;dr Description:** After closing the database Seafile (cloud) detects "changed file" and syncs it.
**Version:** MacPass Version 0.7.1 (17630)
**Plugins:** KeePassHttp

**Comment by mstarke** [comment]
If the file is just opened there should not be any modifications written to it. Does the file get locked? If so, this will cause a write of the database with newly generated seeds for the password and encryption which results in different data and thus a file change on the binary level.

**Comment by Vadammt** [comment]
Yes, it seems you're right. The issue seems to be connected to the ``.lock`` file.
But isn't it sufficient to store the new seeds after the database is saved (or didn't I get the meaning of your comment).

**Comment by mstarke** [comment]
I'm not referring to any ```.lock``` files. Other Keepass clients have used those to indicate that the file should not be modified. MacPass does not generate a ```.lock``` file nor does it respect it. By locking I meant locking the database so you see the password input. This happens automatically after inactivity if you set MacPass to auto-lock.

What do I mean by seeds? The database is encrypted. To ensure a strong encryption, random data is added to the key used for encryption. This random data is never the same for each save and thus the key also changes for each save. This yields different encrypted data and what you end up is a different file on disk every time the database is saved. Not doing this would compromise security vastly. This approach cannot be changes because the KDBX file format is encrypted a whole. Other formats try to mitigate this my storing each item as a encrypted chunk.

Why does MacPass store the file every time you lock it? It removes the file out of memory (at least as much as this is possible in a modern system) and ensures data integrity if you share the file e.g. if another client has the file open both can react to external changes. An older release of MacPass did not do this wich lead to a slew of problems in a synched scenario.

Additionally MacPass supports autosave which will save the file even if you did not close, lock or save it manually reducing the potential risk of data loss to a minimum. Normally autosave should only kick in if you actually change the file so this will not issue saves (and thus file changes) out of the blue.

I'll try to investigate this to see if there is something wrong with MacPass resulting in unnecessary saves and the corresponding file changes.

**Comment by eplanet** [comment]
I'm experiencing the same issue. And since I use a mechanism similar to Vadammt to store the file automatically, I always end up having a new version of MacPass database while having no modifications made to the content itself.

I regularly use Keepass for Windows and various Keepass clients for Linux (KeepassX, KeepassXC, ...), that do not have the same problem: when no modifications are made to the database, the file remain untouched even after being locked.

**Comment by mstarke** [comment]
Do you both lock the database manually or via the auto-lock feature? If so this does explain the changes since even when there are no changes to the file MacPass will write a new one. A possible fix might be to not write a different file if nothing has changed.

**Comment by eplanet** [comment]
I virtually never lock it manually but I have auto-lock enabled. I suppose you got it right, after trying both to auto-lock and manually lock, the file gets changed.

I would love to have the fix you propose ;-)

**Comment by neo-anderson** [comment]
I'd love this feature too. When I quit MacPass, my sync service starts syncing the file. I feel that this could cause sync issues when using MacPass in multiple computers. Unless implementing this feature would reduce security in some way, please consider adding it :)

**Comment by mstarke** [comment]
@neo-anderson does it really save each time you close without any changes since I was unable to reproduce this or does the same save after locking behavior occur for you as well? Does the window title change to "edited" before you save?

**Comment by neo-anderson** [comment]
@mstarke  I'm sorry. I tested again and found that it's not really due to quitting the app, but because I had enabled the option "lock while idle" to just 1 minute, which auto locks the app quickly and thus rewrites the db file. Sorry for the confusion. Would still love to have it not rewrite the file if nothing has changed unless it weakens security in some way.

**Comment by eplanet** [comment]
So I suppose it is solved by [4628c638a8eec65081cfc95106171b0e2fd79b6f](https://github.com/mstarke/MacPass/commit/4628c638a8eec65081cfc95106171b0e2fd79b6f) anyway? 👍

**Comment by mstarke** [comment]
@eplanet it should. In conjunction with searching for a solution I found out that merging doesn't mark the document as changed so I will push out 0.7.4 to fix this as well and it should mitigate the always-write problem.

**Comment by mstarke** [comment]
@neo-anderson If I have a notion what is going on I can point this out, problems arise when some use case doesn't make sense to me and I have no clue of pointing the user to the actual cause so no worries!

**Comment by mstarke** [comment]
To clarify my concerns: Always writing is a save bet so no data will be lost. Skipping the write introduces the risk of data loss if something isn't working as expected so I need to make sure this works as expected. I'm happy that most of issues resulting in lost data with 0.6.2 and before where fixed in 0.7.

**Comment by Vadammt** [comment]
After testing for a while, I don't experience any "wrong" syncs.

**Comment by eplanet** [comment]
I don't agree, I have `Version 0.7.3 (17830)` installed, and the database still gets changed after locking. Would it be possible to reopen the issue? Thanks!

**Comment by Vadammt** [comment]
Which sync tool do you use? <br/>
I'm using **Seafile Client 6.0.7** for Mac and I created a ``seafile-ignore.txt`` in my KeePass library.
```
# Ignore KeePassXC lock files
*.lock
```

**Comment by eplanet** [comment]
I'm using git actually. I know it's not ideal but that's the easiest for me :-D. Anyway, the local database file itself changes (ie, the `*.kdbx` file), the problem is not the lock file.

**Comment by mstarke** [comment]
The fix is not pushed into a release since I had other plans as well and wanted to fold this into 0.8. It might be worth pushing this out as 0.7.4 instead.

**Comment by eplanet** [comment]
I'd love to have the fix ASAP. Thanks a lot for your dedication!

**Comment by mstarke** [comment]
The current continuous build supports this and will not save the database on lock if nothing has changed.
