### ISSUE TITLE
Support KeePass pickpasswordchars autotype

### ISSUE THREAD

**Issue by thor84no** [MacPass/MacPass#859]
**Is your feature request related to a problem? Please describe.**
A common pattern (especially in financial software like Internet banking) in the UK (and likely other places, but those are the ones I'm familiar with) is to prompt for username and password first, then challenge again with a request for 3 specific characters from a "secret word". For example you'll log in with your account number and password, then be asked to provide the 2nd, 4th and 9th character of your secret word (the next time it will be 3 different digits). KeePass provides a mechanism for dealing with this through the autotype sequence keyword "PICKPASSWORDCHARS". If at all possible I would love to get support added for that in MacPass.

**Describe the solution you'd like**
I'd like MacPass to start correctly handling the PICKPASSWORDCHARS autotype sequence keyword. As it is in KeePass, the following autotype sequence can be used to cover the above scenario of 3 characters chosen from your secret word:

`{TAB}{PICKPASSWORDCHARS1:1}{TAB}{PICKPASSWORDCHARS2:1}{TAB}{PICKPASSWORDCHARS3:1}`

This sequence will cause a character picker window to pop up allowing me to click a single button to indicate which character to choose (which will repeat 3 times allowing me to choose one character each time).

Since I share my key file between Windows, Mac, and Linux machines it would be nice if the same autotype sequence could be used across all the platforms.

**Describe alternatives you've considered**
This can be done manually, but the longer the password the more awkward it is to find the Nth character. I don't believe there's any reasonable workaround other than using something other than MacPass.

**Additional context**
PICKPASSWORDCHARS is followed by a number, a colon, and a number. It's my understanding that the first number is an index that will allow re-use (so PICKPASSWORDCHARS1:1 can be used twice in the same sequence to repeat the first selected character) and the second number is how many characters will be included. While I personally only need the case where 1:1, 2:1, 3:1 is used, it would be beneficial if the other use cases for PICKPASSWORDCHARS would be catered to.

Uploading the image showing what this looks like in KeePass doesn't appear to be working, but here is a link: http://keepass.info/filepool/pickchars.png

**Comment by mstarke** [comment]
the current continuous build supports pickchars. The pickpasswordchars placeholder is not supported since it's obsolete. See https://keepass.info/help/base/placeholders.html#plh for reference on how the system works. I might add support for PICKPASSWORDCHARS to allow for old database entries to work.

**Comment by thor84no** [comment]
Thanks, I wasn't aware of that. I've just given it a try and attempted to update my autotype to use the "PICKCHARS" placeholder you mention, but it doesn't seem to be working as described in the KeePass documentation you linked. That might just be me misunderstanding it, but I rewrote the above sequence by:

1. Adding the memorable word as a custom field named "Memorable".
2. Rewriting the above as: `{TAB}{PICKCHARS:Memorable:ID=1,Count=1}{TAB}{PICKCHARS:Memorable:ID=2,Count=1}{TAB}{PICKCHARS:Memorable:ID=3,Count=1}`

As per my reading of the KeePass documentation that should:

- Prompt me 3 times, allowing me to select a single character each time
- Close the window immediately upon clicking a single character
- Index from 1
- Print `{TAB}{first selected character}{TAB}{second selected character}{TAB}{third selected character}`

What I'm seeing at the moment is:

- Prompts me 3 times, allowing me to select a single character each time (good)
- Does not auto close after selecting one character (minor)
- Indexes from 0 (odd, but manageable)
- Prints the wrong characters as well as being different each time I run it. (bug?)

Here's an example of outputs created by having the custom field "Memorable" with the string value "teststring123":

### Selecting 0, 1, 2; one run per line:

```
{TAB}TABe{TAB}s
{TAB}TABee{TAB}s
{TAB}TABeee{TAB}s
# It continues like above...
```
### Selecting 1, 2, 3; one run per line:
```
# First run:
{TAB}e{TAB}s{TAB}t # As expected!
{TAB}e{TAB}s{TAB}t # As expected!
{TAB}e{TAB}s{TAB}t # As expected!
```
### Selecting 2, 3, 4; one run per line:
```
{TAB}s{TAB}TABs
{TAB}s{TAB}TABss
{TAB}s{TAB}TABsss
# It continues like above...
```

I've written actual TAB characters as `{TAB}` above, note that the word "TAB" is also written out for no obvious reason.

**Comment by thor84no** [comment]
According to the app that was with version 0.7.4 (20181201151215-continuous)

**Comment by mstarke** [comment]
I've tried to replicate your findings but couldn't get them. For me all the outputs where the same for each run and every selection was evaluated correctly. But I did find a bug when more than one entry matches for auto-type which resulted in an assertion being raised inside AppKit. This is fixed in the current continuous. Could you try to re-run you examples? I'm curious why you have those strange results.

About you suggestions on auto-closing when all characters are picked an a 1-based start: I'll incorporate them right away.

**Comment by mstarke** [comment]
1-based index and auto-closing on character limit reach is now added as well. Continuous contains all those changes. If you find the time to test them out, I'll be great. Otherwise I'll keep it that way and fix the remaining issues in another release.

**Comment by mstarke** [comment]
I'm keeping this open until the uncertainties are resolved. The current system (with potential bugs) will get released with 0.7.4.

**Comment by thor84no** [comment]
Sorry, I've been away for the holidays. I'll try the latest version and see if I can recreate it at some point this week—hopefully tomorrow.

**Comment by thor84no** [comment]
I'm still seeing the same behaviour. I've made a minor change to my test just so it's easier to see what the expected result is; I've changed the auto type text to `{TAB}{PICKCHARS:Memorable:ID=1,C=1,Hide=false}{TAB}{PICKCHARS:Memorable:ID=2,C=1,Hide=false}{TAB}{PICKCHARS:Memorable:ID=3,C=1,Hide=false}` (I've added `Hide=false`, but otherwise it should be the same).

The indexes are now correct, but the printed text is not. One thing I've noticed is it only occurs if the `{TAB}` is in the autotype string. If I remove all instances of that it seems to work OK, but those are mandatory for the appropriate typing of this type of password. It's also still causing each iteration that messes up to modify the next one. This seems tied to the individual index rather than the combination, so if I choose 3,4,5 and 5 messes up, then doing 5,6,7 will include the messed up version of the character in the 5th position.

**Comment by mstarke** [comment]
I have created a database and attached it (Password: test) and tried to reproduce your setup with no luck. I do not get any TABs being typed, the keys get sent correctly every time.

Can you try again with the attached database?
[Pickchars.kdbx.zip](https://github.com/MacPass/MacPass/files/2739841/Pickchars.kdbx.zip)

**Comment by thor84no** [comment]
I've just tried it with your database and yes, I'm still having the same issue. Down to the sequence 2,3,4 working correctly, but almost all other combinations not working. Very odd. I'm on High Sierra (10.13.6) if that makes any difference.

**Comment by mstarke** [comment]
Mh. I'll try to find a test system or set a VM with 10.13 but that's going to take a while. I tried a lot of combinations but all work just as expected.

**Comment by mstarke** [comment]
I haven't found the time to debug this and cannot reproduce the issue so I'll move it to the next milestone in hope for a solution…

**Comment by ericmoret** [comment]
Knowing 0.8.1 has already been released. Does that mean that this feature is out yet?

**Comment by orestesgaolin** [comment]
This is available in the latest version, works really well I must say. The one thing I'm missing is ability to cancel that. Once you enable pick chars with following autotype config: `{PICKCHARS:Password:C=5}{ENTER}` and trigger that there's no way to cancel it

![CleanShot 2023-03-17 at 13 12 38](https://user-images.githubusercontent.com/16854239/225901035-9d88b18e-e06a-4961-8b89-719e3dde4771.png)

**Comment by mstarke** [comment]
Since this is in the execution of a autotype sequence there is currently no mechnism to cancel the execution, since it wasn't really necessary (or possible)
